# Generated by Django 2.1.3 on 2018-12-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lime_', '0002_remove_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=2000)),
            ],
        ),
    ]
